### ISSUE TITLE
Settle multiple unpaid invoices with one payment entry

### ISSUE THREAD

**Issue by barredterra** [alyf-de/banking#73]
Imagine we have one **Bank Transaction** for $500 to be reconciled with five unpaid invoices for $100 each. Currently, the **Bank Reconciliation Tool** would create five **Payment Entries**. But there was only one payment. To split it up into five **Payment Entries** may cause confusion. Instead, we should create one **Payment Entry** with five reference rows.

**Comment by aa-prashant** [comment]
Hi, any update on the issue?

**Comment by barredterra** [comment]
Work in progress, see the pull request linked above.

**Comment by aa-prashant** [comment]
Any timeline when it will be merged?

**Comment by marination** [comment]
@aa-prashant https://github.com/frappe/erpnext/pull/37859 needs to be merged and then I can continue with the fix linked above. So perhaps a week or so.

**Comment by aa-prashant** [comment]
Hi @marination , do we have any update on this one? I found that the said PR is merged.
