### ISSUE TITLE
Feature Request - Setting for Selecting the date of payment entry.

### ISSUE THREAD

**Issue by aa-prashant** [alyf-de/banking#81]
Here is the use case -
The customer makes payment on 1 Nov
The account department does reco activity on 3 Nov
Payment Entry for that payment was created on 3 Nov
Customer Scorecard/Rating gets affected due to delay in payment.

Feature Request:-
Check the box in the Reco tool setting page -
- Make Payment entry on the transaction date.

**Comment by barredterra** [comment]
Probably this can even be the default. We want the payment to affect our accounting books at the date of the bank transaction, not at the date of reconciliation. 🤔 But it might create issues with closed accounting periods.

**Comment by aa-prashant** [comment]
Yes your concern is right!
But ideally all other accounting software does it this way only. (Tally, Xero, Myob). The voucher (payment entry) date is the bank date. 

But anyways, this is the purpose of accounting periods and its closing.

And if you have bank transactions from your closed accounting period. then an error can be thrown that ‘this transaction belongs to the closed accounting period, you are not allowed to create payment entries in this period, please ask your administrator’

we can discuss more on this. 
see ya!

**Comment by marination** [comment]
@aa-prashant This ticket should be resolved already. The closed accounting period is considered as well
