### ISSUE TITLE
Validate Reconciliation Amounts

### ISSUE THREAD

**Issue by marination** [alyf-de/banking#84]
Make sure that, in total, we don't move more money than can be found in the Bank Transaction. I. e. if the Bank transaction is for $100, it should not be possible to reconcile $75 and create a journal entry for $80, because the sum is > $100

**Comment by marination** [comment]
- If a new PE/JV is created via the create tab (without edit in full page), then its made only for the unallocated amount ✅ 
- If a new PE/JV is created via the create tab (**with** edit in full page), then you can technically create it for an amount > unallocated amount. But it is then partially allocated to the bank transaction
		- Eg. For a BT of 100 EUR, 50 EUR was reconciled via a Purchase Invoice
		- For the remaining a PE was made via edit in full page, for 80 EUR and submitted.
		- On submission, it is reconciled with the BT but only 50 EUR is allocated in the BT.
		- When this PE reappears in the Reco matching tab, it will show outstanding = 30 EUR (80 total - 50 allocated)

In principle a PE that was created for a BT should not be allowed to have more than the unallocated amount in the BT. But the user can interpret it as just generally making a PE against many BTs. I don't think we should control that.

This ticket can be closed but I am not sure.

@barredterra What do you think ?

**Comment by barredterra** [comment]
I agree, the current behaviour sounds fine.
