### ISSUE TITLE
Paying the last invoice with full amount even the created payment entry in Bank transaction has less amount

### ISSUE THREAD

**Issue by aa-prashant** [alyf-de/banking#85]
<img width="1416" alt="Bank Transaction" src="https://github.com/alyf-de/banking/assets/31651947/088fa9b1-7874-48cd-8670-0c414af8bc0a">

The Amount of Payment Entry showing in the bank transaction is $20.07 - Because that is the remaining amount

<img width="1325" alt="Actual " src="https://github.com/alyf-de/banking/assets/31651947/78931c27-ed6f-46f9-8901-5431bb9d83df">

The Actual Amount paid in the payment entry is $335 (The actual Amount of the Invoice), It has paid of the complete invoice, but it should have been 20.07 and partially paying the invoice.

This is a terrifying issue, and I request you to solve it quickly.
I am also requesting you to provide a script which can diagnose and track all the payments/invoices which are fully paid by these issues.
(We can have a script which tracks payment entries in the bank transaction child table and the respective payment entry document and finds out if there is a difference in amount.)

**Comment by aa-prashant** [comment]
Here is the full screenshot, Showing the payment entry number

<img width="1420" alt="Screenshot 2023-11-17 at 7 04 27 PM" src="https://github.com/alyf-de/banking/assets/31651947/d92fdb0c-7085-4204-a2eb-1844f135fe1b">

**Comment by barredterra** [comment]
Hi, @aa-prashant kindly share the version of the banking app you're using. (We've already resolved very similar issues, so you might still experience them if you're on an older version.)

**Comment by aa-prashant** [comment]
> Hi, @aa-prashant kindly share the version of the banking app you're using. (We've already resolved very similar issues, so you might still experience them if you're on an older version.)

ALYF Banking: v0.0.9 (version-14)

**Comment by marination** [comment]
this is in regards to reco of an unpaid SI against a bank transaction with lesser amount to allocate right ?
@barredterra shouldn't that be fixed by https://github.com/alyf-de/banking/blob/171895a31c762bcba75d835efdf7eac0a8f0e1ca/banking/overrides/bank_transaction.py#L50

**Comment by marination** [comment]
@aa-prashant the issue has been fixed and released. You could update your banking instance.

**Comment by aa-prashant** [comment]
> @aa-prashant the issue has been fixed and released. You could update your banking instance.

Thank you so much to the team, will try and get the feedback here.

Thank you
