### ISSUE TITLE
Auto Reconcile button not working

### ISSUE THREAD

**Issue by KerollesFathy** [alyf-de/banking#95]
when clicked on auto reconcile button using **Bank Reconciliation Tool Beta**

![WhatsApp Image 2024-04-24 at 2 03 43 PM](https://github.com/alyf-de/banking/assets/74776193/cb0cf41d-2a9f-4368-9d12-90e328012300)
 
I think the solution will be adding  `common_filters` parameter to `get_matching_queries`

**Comment by barredterra** [comment]
This is just a remnant from the original Bank Reconciliation tool, we're not actively supporting it. I guess we should simply remove it, then. What do you think, @marination?

**Comment by marination** [comment]
As discussed: patch + work on a better matching algorithm for the future
